version: '3.8'

services:
  # Servicio de la aplicación Django
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn user_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles # Monta el volumen para archivos estáticos
    environment:
      - SECRET_KEY=grupo8
      - DB_NAME=pedidos_user_service
      - DB_USER=root
      - DB_PASSWORD=
      - DB_HOST=db
      - DB_PORT=3306
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,user-service
    depends_on:
      - db
    networks:
      - user-network

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_user_service
      MYSQL_USER: user
      MYSQL_PASSWORD: yes # Contraseña vacía para el usuario root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" # Mapea el puerto del contenedor a un puerto diferente en el host (3307) para evitar conflictos con XAMPP
    networks:
      - user-network

  # Proxy reverso NGINX
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static # Monta el volumen para archivos estáticos
    depends_on:
      - user-service
    networks:
      - user-network

volumes:
  mysql-data:
  static_volume: # Define el volumen para archivos estáticos

networks:
  user-network:
    driver: bridge
